# Generated by Django 3.1 on 2020-09-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idTaxi', models.IntegerField(default=0)),
                ('dropoff_latitude', models.FloatField(default=0)),
                ('dropoff_longitude', models.FloatField(default=0)),
                ('passenger_count', models.IntegerField(default=0)),
                ('pickup_latitude', models.FloatField(default=0)),
                ('pickup_longitude', models.FloatField(default=0)),
                ('hour_of_day', models.IntegerField(default=0)),
                ('day_of_week', models.IntegerField(default=0)),
                ('day_of_year', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('eucl_distance', models.FloatField(default=0)),
                ('manh_distance', models.FloatField(default=0)),
                ('fare_amount', models.FloatField(null=True)),
                ('estimated_fare', models.FloatField(null=True)),
            ],
            options={
                'unique_together': {('idTaxi',)},
            },
        ),
    ]
